### ISSUE TITLE
cannot work for current new bing

### ISSUE THREAD

**Issue by Co1lin** [transitive-bullshit/bing-chat#17]
Hi! I find it cannot handle responses from new bing now. It could work several hours ago, but now it cannot. I think something is changed in the responses of current new bing.

Error log:

```js
file:///app/node_modules/bing-chat/build/index.js:148
              const msg = update.arguments[0].messages[0];
                                                      ^

TypeError: Cannot read properties of undefined (reading '0')
    at WebSocket.<anonymous> (file:///app/node_modules/bing-chat/build/index.js:148:55)
    at WebSocket.emit (node:events:512:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:512:28)
    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/app/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/app/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
```

**Comment by dickymuliafiqri** [comment]
Refer to this [PR](https://github.com/transitive-bullshit/bing-chat/pull/18)

You can implement this fix yourself if you in hurry

**Comment by Co1lin** [comment]
I tested #18, and it worked! Thank you!
