### ISSUE TITLE
ERROR in node:crypto 

### ISSUE THREAD

**Issue by Ankushnegi014** [transitive-bullshit/bing-chat#37]
i am getting this error while importing the bing-chat into the component

ERROR in node:crypto
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /home/ankush/bingchat/node_modules/webpack/lib/NormalModule.js:838:25
    at Hook.eval [as callAsync] (eval at create (/home/ankush/bingchat/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/ankush/bingchat/node_modules/tapable/lib/Hook.js:18:14)
    at Object.processResource (/home/ankush/bingchat/node_modules/webpack/lib/NormalModule.js:835:8)
    at processResource (/home/ankush/bingchat/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
    at iteratePitchingLoaders (/home/ankush/bingchat/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
    at runLoaders (/home/ankush/bingchat/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
    at NormalModule._doBuild (/home/ankush/bingchat/node_modules/webpack/lib/NormalModule.js:825:3)
    at NormalModule.build (/home/ankush/bingchat/node_modules/webpack/lib/NormalModule.js:969:15)
    at /home/ankush/bingchat/node_modules/webpack/lib/Compilation.js:1377:12

webpack compiled with 1 error and 1 warning

**Comment by izcoser** [comment]
I had this in Next.js when I tried to call bing from the client side. My solution was to move to the backend.

**Comment by davicyyo** [comment]
It solves my problem:

`npm install webpack-node-externals --save-dev`

Webpack:
`const nodeExternals = require('webpack-node-externals');`
`module.exports = {
  ...
  externals: [nodeExternals()],
};`
