### ISSUE TITLE
unexpected HTTP error createConversation 403

### ISSUE THREAD

**Issue by xhzth7091** [transitive-bullshit/bing-chat#40]
npx tsx d:\code\python\binggpt\bing-chat-main\demos\demo.ts 
windows 11

✖ What are today’s top stories in the United States?
Error: unexpected HTTP error createConversation 403: Forbidden
    at <anonymous> (d:\code\python\binggpt\bing-chat-main\src\bing-chat.ts:317:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BingChat.sendMessage (d:\code\python\binggpt\bing-chat-main\src\bing-chat.ts:65:28)
    at async oraPromise (file:///d:/code/python/binggpt/bing-chat-main/node_modules/ora/index.js:397:18)
    at main (d:\code\python\binggpt\bing-chat-main\demos\demo.ts:20:15)

I can log in https://www.bing.com,Can chat normally
![image](https://github.com/transitive-bullshit/bing-chat/assets/13980546/1564d426-0f37-42b0-a2c2-13fd475b272c)

cookie
![RDBBN1J1 @~%N2($M}0 E9J](https://github.com/transitive-bullshit/bing-chat/assets/13980546/c5ba5b9a-25ae-45b7-b73a-093e9f1c8615)

![1F)~% XG$XM5GZ7F`_%L HP](https://github.com/transitive-bullshit/bing-chat/assets/13980546/3b3af0a2-cae5-4c96-b930-24fca7fe2f13)

Why would you report 403?

**Comment by RaschidJFR** [comment]
Have you tried not using the cookie at all? I started getting 503 until I removed it.

**Comment by bestK** [comment]
``` shell
yarn add bing-chat-patch

#Create your bing proxy, see https://github.com/adams549659584/go-proxy-bingai

export BING_HOST=<your_bing_host> #Please do not include https/http.
```

usage
``` ts
import { BingChat } from 'bing-chat-patch';
import dotenv from 'dotenv';
dotenv.config();
```
